### PR TITLE
deps: golangci-lint to 1.55.2

### PR DESCRIPTION
**Pull request by fmartingr**
#### Summary

This pull requests upgrades `golangci-lint` to the latest version to prevent issues in plugin workflows.

### CODE REVIEW

**Review by toninis — APPROVED** [review]
🚀

**Review by hanzei — CHANGES_REQUESTED** [review]
I'm very hesitant to make this change, as it will most likely break the lintin for existing plugin. `golangci-lint` is known if breaking stuff often.

Is there a patch version that we can use instead?

**Comment by fmartingr** [comment]
> I'm very hesitant to make this change, as it will most likely break the lintin for existing plugin. `golangci-lint` is known if breaking stuff often.
> 
> Is there a patch version that we can use instead?

The next release after 1.52.2 was the minor v1.53.0.

**Comment by hanzei** [comment]
Does the pipeline run successfully with `v1.53.0`?

**Comment by fmartingr** [comment]
> Does the pipeline run successfully with `v1.53.0`?

Next one that works correctly in my local machine is `v1.54.0`.

**Review by hanzei — APPROVED** [review]
I'm fine with merging the change as long we fix all linter issues that arise due to it after the merge.

**Comment by fmartingr** [comment]
> I'm fine with merging the change as long we fix all linter issues that arise due to it after the merge.

I'm not watching all plugin repos, feel free to ping me around so I can take a look and fix pipelines.

**Pull request merged**
